Feat/containers
stackhpc/slurm_image_builder pull request #15
Opened 2023-02-14 10:21 UTC by sjpb

Add `podman`, `podman-compose` and `apptainer` to image.

2023-02-14 10:44 UTC, sjpb commented
Will be image `openhpc-230214-1026.qcow2`

2023-02-14 13:48 UTC, sjpb commented
Will be image `openhpc-230214-1147.qcow2`

2023-02-14 13:54 UTC, sjpb commented
fff34b1 reduced image size from 8.01GB to 7.91GB.

2023-02-15 12:49 UTC, sjpb commented
Built image `openhpc-230215-1202.qcow2`

2023-02-17 11:21 UTC, m-bull requested changes

2023-02-17 11:21 UTC, m-bull commented on roles/builder/defaults/main/users.yml
> +prometheus_db_dir: /var/lib/prometheus # will get moved to appliances state dir by appliance
Should this go in a `prometheus.yml` file?

2023-02-17 11:21 UTC, m-bull commented on roles/builder/tasks/users.yml
> +    - name: Add groups
Remove whitespace from the start of all lines in here

2023-02-17 15:03 UTC, sjpb commented
Built image `openhpc-230217-1440.qcow2`

2023-02-17 15:06 UTC, m-bull approved these changes

2023-02-17 15:06 UTC, merged